from html_flashcard_generator import HTMLFlashCardGenerator
html_flashcard_generator = HTMLFlashCardGenerator()
html_flashcard_generator.create_all_flash_card_group_by_CEFR()
html_flashcard_generator.print_topic_color()
# html_flashcard_generator.create_demo_csv()
# html_flashcard_generator.create_html_flashcard_from_csv("demo_file")
